name: DocFX Build and Publish

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]
    
jobs:
  DocFx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: Doc/docfx.json
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Doc/_site
        force_orphan: true
